# Generated by Django 4.0.5 on 2022-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('nomProducto', models.CharField(max_length=80, verbose_name='Nombre del producto')),
                ('nomCategoria', models.CharField(max_length=80, verbose_name='Nombre Categoría')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('porcDesctoSubscriptor', models.IntegerField(verbose_name='Descuento Subscriptor')),
                ('porDesctoOferta', models.IntegerField(verbose_name='Descuento Oferta')),
                ('urlImagenProducto', models.CharField(max_length=300, verbose_name='Imágen Producto')),
            ],
        ),
    ]
