# Generated by Django 4.0.5 on 2022-07-04 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0002_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nroFactura', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro. de factura')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('montoTotal', models.IntegerField(verbose_name='Monto total')),
                ('estadoActual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado actual')),
                ('idProd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tienda.producto', verbose_name='ID de Producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ID de usuario')),
            ],
        ),
    ]
